version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/WolfgangMau/chamgo
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: ./build
  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/WolfgangMau/chamgo
    steps:
      - checkout
      - run: make package
      - run: go get github.com/aktau/github-release
      - run: github-release info --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME}
      - run: github-release release --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name ${CIRCLE_TAG} --description ${CIRCLE_TAG} --pre-release
      - run: for f in build/*.tar.gz; do github-release upload --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name `basename ${f}` --file ${f}; done
      - run: github-release edit --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name ${CIRCLE_TAG} --description ${CIRCLE_TAG}

workflows:
  version: 2
  build_and_release:
      jobs:
        - build:
            filters:
              tags:
                only: /.*/
        - release:
            requires:
              - build
            filters:
              tags:
                 only: /v[0-9]+(\.[0-9]+)*(-.*)*/
              branches:
                 ignore: /.*/